### PR TITLE
[Translation][spanish] - pointers

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
@pjcalvo I think this is ready for review 😊 Feel free to phrase it in the preferred style for the project

**Review by pjcalvo — APPROVED** [review]

**Comment by pjcalvo** [comment]
Beautiful, feel free to merge.

**Comment by mdelapenya** [comment]
I do not have permissions 😅

**Comment by pjcalvo** [comment]
Merged @mdelapenya Muchas gracias. Looking forward to review more work from you. ;)

**Pull request merged**
