### PR TITLE
[Translation][French] - variables.article

### PR DESCRIPTION
**Pull request by PhilippeZeitoun**

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
You have rights to merge to the French branch. But please ask the team how they are doing things.

**Comment by scraly** [comment]
on my side I can't create a new branch, only a fork

**Comment by ardan-bkennedy** [comment]
You can push code to the french branch. I always through the team would treat the branch as their main.  Let me look at your rights.

**Comment by ardan-bkennedy** [comment]
You have Write access. I don't know what you need to create a new branch?

**Comment by scraly** [comment]
I didn't know I needed to push everything in an existing branch, in the "french" branch :)

So in order to not do mistakes, is it possible to tell us what are the important things to know in order to help on the translation?

thanks

**Comment by PhilippeZeitoun** [comment]
Hi,
On my side I forked the project (I can't push directly from a direct clone), created a french-translation branch on my fork (because I didn't want to broke french branch), then I PR from my fork (french-translation) to main.
As french branch on gotour has not been translated at all and seems late from main may be it should be good to synchronize it then we could PR on it ?
@scraly I just finished to translate struct-type.article but I'll wait we synchronize for the process before proceeding with a new PR. Could you merge rebase the french branch (it's what git asked from me) ?

**Comment by ardan-bkennedy** [comment]
@PhilippeZeitoun  you have rights now to push to the French branch

**Comment by PhilippeZeitoun** [comment]
Ok thanks Bill I change my local branch to french and I push.

**Pull request closed without merging**
