### PR TITLE
Fix eng content tests; run tests via GitHub Actions

### PR DESCRIPTION
**Pull request by alexandear**
The PR fixes the test that checks code examples in the `_content/tour/eng` directory and adds GitHub Actions workflow to run tests on each PR or push to the `main` branch.

Now, running `go test -v ./...` works flawlessly.

I have divided the PR into separate logical commits to facilitate review. Each commit corresponds to one logical change.

### Changes:

- Fixed `TestContent` to work with `//go:build` build constraint. It's worth mentioning that the tour from Go team's uses `// +build` comments, but this gotour uses `//go:build` (introduced here #45). Thus, `TestContent` has been adapted to work with `//go:build`.
- Moved `content_test.go` to the root because `go test` skips the `_content` folder when detecting tests.
- Renamed `TestContent` to `TestContentEngTour`. Run tests only for `eng` directory. 
- Retained only one `content_test.go` that checks examples for all languages.
- Added the missing `OMIT` to all code snippets.
- Added the build constraint `nobuild` to code snippets that cannot be compiled via `go build`.
- Added the build constraint `norun` to code snippets that cannot be executed. Note that we cannot use `no-run` (with a hyphen) as a build constraint name.

### CODE REVIEW

**Comment by alexandear** [comment]
Follows #260

**Comment by ardan-bkennedy** [comment]
This needs to merge to bill/testing

**Comment by ardan-bkennedy** [comment]
Not sure why? I will need to merge it into main anyway. I can easily do that in this testing branch.

**Comment by ardan-bkennedy** [comment]
I can delete this branch and give you a new one to merge to?

**Comment by alexandear** [comment]
> Not sure why? I will need to merge it into main anyway. I can easily do that in this testing branch.

I'm assuming we are using the GitHub [flow](https://docs.github.com/en/get-started/using-github/github-flow). This flow includes the following steps:

1. Forking a repository: I forked `ardanlabs/gotour` into `alexandear/gotour`.
2. Making changes and creating a PR: I made changes in `alexandear:fix-content-test` and created this PR.
3. Reviewing the PR by maintainers and adding comments: You need to review the PR either using the GitHub UI or by checking it out locally.
4. Addressing comments: I need to address your comments on my PR.
5. Merging the PR into the default branch by maintainer: After I have addressed the comments, you need to merge this PR into `main` by pressing the button "Merge". GitHub will automatically mark the PR as "Merged".

**Comment by ardan-bkennedy** [comment]
The PR is TOO BIG and it scares me. I have to review it and make sure nothing breaks. I need it in my testing branch I provided if you want to see this merged.

**Comment by ardan-bkennedy** [comment]
I created a new bill/testing2 branch for this PR.

**Comment by alexandear** [comment]
I reverted all changes related to local translations (they will be fixed later) and retained only the fixes for examples in the `eng` directory to simplify the review process.

Only two files require thorough review:

- .github/workflows/pr.yml
- content_test.go

All other modifications add `nobuild` and `norun` build constraints to examples.

Also, the tests are passed on CI: https://github.com/ardanlabs/gotour/actions/runs/9681636341/job/26712671977?pr=262

**Comment by ardan-bkennedy** [comment]
I will NOT being merging this into main directly. You will need to merge this into bill/testing2 so I can gain access to the code directly and run my own test and review. If you are not willing to do this, I can't accept it.  I apprecaite the time and effort you are putting into this. That is why I am asking you for this again.

**Comment by alexandear** [comment]
@ardan-bkennedy changed branch from `main` to `bill/testing2`.

**Comment by ardan-bkennedy** [comment]
I made a some minor refactoring changes. This code is nice and I was able to see what you did. Pull down these changes and you can give me a PR to main and I will accept it.  Make sure you have your name in the CONTRIBUTORS file please.

**Comment by alexandear** [comment]
Thank you. Created #263.

My name already in the CONTRIBUTORS file.

**Pull request merged**
