### PR TITLE
fix: replace example number 1 by 6 at data race article

### PR DESCRIPTION
**Pull request by WendelHime**
Fixing typo

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
First, thank you for this! I need you to add yourself to the CONTRINUTORS file.

Second, There are 8 languages now, have you checked all of them for this mistake.

**Comment by WendelHime** [comment]
Hi Bill, yes I've checked all languages. Portuguese and Polish was already fixed!

**Comment by ardan-bkennedy** [comment]
Are you already in the CONTRIBUTORS file?

**Comment by WendelHime** [comment]
Probably nop, let me add, 1s

**Pull request merged**
