### PR TITLE
[Translation] [spanish]: update branch with recent changes

### PR DESCRIPTION
**Pull request by mdelapenya**
Including the following commits:

- **fixing code example style**
- **fixing code run style**
- **fixing data-race article for code problem**
- **German Transaltion (#236)**
- **upgraded to 1.22**
- **upgraded deps**
- **fix: replace example number 1 by 6 at data race article (#238)**
- **fixing code example style**
- **fixing code run style**
- **fixing data-race article for code problem**
- **upgraded to 1.22**
- **fix: replace example number 1 by 6 at data race article**

I also resolved conflicts regarding the addition of the German translation, and the vendored dependencies.

### CODE REVIEW

**Comment by mdelapenya** [comment]
@pjcalvo a new update for the Spanish lang, this one just updating it with the recent changes in main.

@ardan-bkennedy I wonder if it's possible to merge a language branch without making it public, so that the changes in the core are applied to that WIP language when they are introduced. Otherwise, we have to go resolving conflicts and keeping track of the changes manually trying not to forget any of them. You know, manually resolving conflicts could lead to mistakes.

**Comment by pjcalvo** [comment]
This is a good idea... would be easier to resolve problems

**Review by pjcalvo — APPROVED** [review]

**Comment by pjcalvo** [comment]
@mdelapenya i am going to merge this Pr, can u open an issue and tag Bill to discuss if there is a solution to merge branches without making the language public .

Thanks

**Comment by mdelapenya** [comment]
Done in https://github.com/ardanlabs/gotour/issues/240, thanks!

**Pull request merged**
