### PR TITLE
adjusts a typographic error

### PR DESCRIPTION
**Pull request by GoesToEleven**
Small change, Bill! Recording this in a video, also, to show a pull request.

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
Please add yourself to the CONTRIBUTORS file.

**Comment by GoesToEleven** [comment]
Done @ardan-bkennedy - Thank you!

**Comment by ardan-bkennedy** [comment]
I'm realizing now all you did was remove the line breaks, which doesn't matter in the final rendering of the content. I added those line breaks because my editor is set to not wrap lines and I didn't want the content to go past column 80. 

Is there a reason you removed these line breaks related to how the content was rendering?

**Comment by ardan-bkennedy** [comment]
I am going to close the PR.

**Pull request closed without merging**
