### PR TITLE
fix: typo Iyou

### PR DESCRIPTION
**Pull request by skibish**
I assume this is a typo and it should be "you" instead of "Iyou".

### CODE REVIEW

**Comment by ardan-bkennedy** [comment]
Thanks, are you listed in the CONTRIBUTORS file yet?

**Comment by skibish** [comment]
No, I am not. Should I add myself to it?

**Comment by ardan-bkennedy** [comment]
Yes Please so I can approve the PR

**Comment by skibish** [comment]
Done!

**Pull request merged**
